project_id = "lypkliuanenevghglxcq"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.classificar-prioridade]
verify_jwt = false

[functions.gerar-relatorio-chamados]
verify_jwt = false

[functions.processar-pdf-salus]
verify_jwt = false
